apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-release # Replace with your desired Helm release name
  namespace: practice1
spec:
  interval: 2m
  chart:
    spec:
      chart: ./charts/my-parent-chart # Path to your local Helm chart directory
      version: '0.1.10'
      sourceRef:
        kind: GitRepository
        name: gcp-practice
        namespace: default
      interval: 1m