apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-release # Replace with your desired Helm release name
  namespace: practice
spec:
  interval: 5m
  chart:
    spec:
      chart: my-parent-chart # Path to your local Helm chart directory
      version: '0.1.10'
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
      interval: 1m