name = "my-cluster"
location = "northamerica-northeast2"
release_name = "test-chart"
project_id = "robotic-circle-359714"
chart = "my-parent-chart"
helm_chart_version = "0.1.10"
namespace_name = "practice"