apiVersion: v1
kind: Service
metadata:
  name: argocd-server-1
  namespace: argocd
spec:
  selector:
    app: argocd-server
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080  # Assuming Argo CD server is running on port 8080 inside the pods
  type: LoadBalancer
