apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: {{ .Values.image.repository }}
          tag: {{ .Values.image.tag }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: myrootpassword  # Replace with your MySQL root password
            - name: MYSQL_DATABASE
              value: mydatabase      # Replace with your database name
            - name: MYSQL_USER
              value: myuser          # Replace with your database username
            - name: MYSQL_PASSWORD
              value: mypassword      # Replace with your database password
          ports:
            - containerPort: 3306
