apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-ingress
spec:
  rules:
    - host: example.io
      http:
        paths:
          - path: /mysql
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-mysql-service
                port:
                  number: 3306
