name: Deploy to Argo CD

on:
  workflow_dispatch: {}
  push:
    branches:
    - main # Change this to your main branch name
    paths:
    - 'charts/my-parent-chart/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Argo CD CLI
        run: |
          curl -LO https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Log in to Argo CD
        run: argocd login --insecure --username admin --password ${{ secrets.ARGOCD_PASSWORD }} localhost:8080

      - name: Sync Argo CD Application
        run: argocd app sync  --sync-option Prune=false

